apiVersion: apps/v1
kind: Deployment
metadata:
  name: jochemwhite-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jochemwhite-frontend
  template:
    metadata:
      labels:
        app: jochemwhite-frontend
    spec:
      containers:
      - name: jochemwhite-frontend
        image: ghcr.io/jochemwhite/jochemwhite:24dff75a06990d127384419d20853ee1034f7ea9
        ports:
        - containerPort: 3000
        # envFrom:
        # - secretRef:
        #     name: jochemwhite-frontend