apiVersion: apps/v1
kind: Deployment
metadata:
  name: jochemwhite-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jochemwhite-frontend
  template:
    metadata:
      labels:
        app: jochemwhite-frontend
    spec:
      containers:
      - name: jochemwhite-frontend
        image: ghcr.io/jochemwhite/jochemwhite:3508fc636fe6fa3de3195a86b79413fa8cfb6bef
        ports:
        - containerPort: 3000
        # envFrom:
        # - secretRef:
        #     name: jochemwhite-frontend