apiVersion: apps/v1
kind: Deployment
metadata:
  name: jochemwhite-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jochemwhite-frontend
  template:
    metadata:
      labels:
        app: jochemwhite-frontend
    spec:
      containers:
      - name: jochemwhite-frontend
        image: ghcr.io/jochemwhite/jochemwhite:f3d373dd6eeed8cc3a9e4c8983679eb90ce507f3
        ports:
        - containerPort: 3000
        # envFrom:
        # - secretRef:
        #     name: jochemwhite-frontend