apiVersion: apps/v1
kind: Deployment
metadata:
  name: jochemwhite-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jochemwhite-frontend
  template:
    metadata:
      labels:
        app: jochemwhite-frontend
    spec:
      containers:
      - name: jochemwhite-frontend
        image: ghcr.io/jochemwhite/jochemwhite:e5561d911308cc9365d70a211bb6f6c4939ccf71
        ports:
        - containerPort: 3000
        # envFrom:
        # - secretRef:
        #     name: jochemwhite-frontend